# Generated by Django 5.2.12 on 2026-03-21 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("total_rows", models.PositiveIntegerField()),
                ("seats_per_row", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SeatStatus",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("reserved", "Reserved"), ("purchased", "Purchased")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row", models.CharField(max_length=2)),
                ("number", models.PositiveIntegerField()),
                ("seat_label", models.CharField(max_length=5)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="seats", to="seats.room"
                    ),
                ),
            ],
            options={
                "ordering": ["row", "number"],
            },
        ),
    ]
