# Generated by Django 5.2.12 on 2026-03-21 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cinema_sessions", "0002_initial"),
        ("seats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seatstatus",
            name="locked_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="seatstatus",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="statuses", to="seats.seat"
            ),
        ),
        migrations.AddField(
            model_name="seatstatus",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_statuses",
                to="cinema_sessions.cinemasession",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("room", "row", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="seatstatus",
            unique_together={("session", "seat")},
        ),
    ]
