# Generated by Django 5.2.12 on 2026-03-21 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=255)),
                ("cast", models.TextField(blank=True, default="")),
                ("poster_url", models.URLField(blank=True, null=True)),
                ("release_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-release_date"],
            },
        ),
    ]
