# Generated by Django 5.2.12 on 2026-03-21 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cinema_sessions", "0001_initial"),
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemasession",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="seats.room"
            ),
        ),
    ]
